# Site settings
title: Wendy's Blog
SEOTitle: Wendy的博客 | Wendy's Blog
header-img: img/post-bg-desk.jpg
email: youlinai233@gmail.com
description: "Little record of my life, talks other than programming."
keyword: "Wendyltanpcy, Wendy's Blog, Wendy的博客, 生活, 记录, 编程, 分享"
url: "https://wendyltan.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/wendyltan/wendyltan.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "足够细腻去触碰生活，内心才能更加坚强"
sidebar-avatar: /img/asuka.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: true
weibo_username:     折木柚璃桑
github_username:    wendyltan




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 629c3481153700357053                           #生成的clientID
  clientSecret: 3de01b746f16f23075fba964d9fb3ce474d2a75e    #生成的clientSecret
  repo: BlogComment   #仓库名称
  owner: wendyltan    #github用户名
  admin: wendyltan
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  perPage: 15 #每页多少个评论
  pagerDirection: last #排序方式是从旧到新（first）还是从新到旧（last）
  createIssueManually: true #如果当前页面没有相应的 isssue ，且登录的用户属于 admin，则会自动创建 issue。如果设置为 true，则显示一个初始化页面，创建 issue 需要点击 init 按钮。




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "bilibili",
        href: "https://bilibili.com"
    },{
        title: "Github",
        href: "https://github.com"
    }
]

timezone: CN